//
// @author LazyBear
//
study("Premier Stochastic Oscillator [LazyBear]", shorttitle="PSO_LB")
stochlen = input(8, title="Stoch length")
smoothlen = input(25, title="Smooth length")
sk = stoch( close, high, low, stochlen)
len = round(sqrt( smoothlen ))
nsk = 0.1 * ( sk - 50 )
ss = ema( ema( nsk, len ), len )
expss = exp( ss )
pso = ( expss - 1 )/( expss + 1 )
plot( pso, title="Premier Stoch", color=black, linewidth=2 )
plot( pso, color=iff( pso < 0, red, blue ), style=histogram )
plot(0, color=gray)
plot( 0.2, color=blue, style=3 )
plot( 0.9, color=blue)
plot( -0.2, color=red, style=3)
plot( -0.9, color=red )



For long trades: 
(1) Premier stochastic crosses below 0.90 
(2) premier stochastic crosses below 0.20 

For short trades: 
(1) Premier stochastic crosses above -0.90 
(2) premier stochastic crosses above -0.20 

More info on the trading zones and other nuances: 
http://www.investopedia.com/articles/trading/10/premier_stochastic_oscillator_explained.asp 